<?php
/**
 * CalendarApiTest
 * PHP version 8.1
 *
 * @package  EsiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.33
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace EsiClient\Test\Api;

use EsiClient\Configuration;
use EsiClient\ApiException;
use EsiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CalendarApiTest Class Doc Comment
 *
 * @package  EsiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CalendarApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getCharactersCharacterIdCalendar
     *
     * List calendar event summaries.
     *
     */
    public function testGetCharactersCharacterIdCalendar()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCharactersCharacterIdCalendarEventId
     *
     * Get an event.
     *
     */
    public function testGetCharactersCharacterIdCalendarEventId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCharactersCharacterIdCalendarEventIdAttendees
     *
     * Get attendees.
     *
     */
    public function testGetCharactersCharacterIdCalendarEventIdAttendees()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for putCharactersCharacterIdCalendarEventId
     *
     * Respond to an event.
     *
     */
    public function testPutCharactersCharacterIdCalendarEventId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
