<?php
/**
 * KillmailsApiTest
 * PHP version 8.1
 *
 * @package  EsiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.33
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace EsiClient\Test\Api;

use EsiClient\Configuration;
use EsiClient\ApiException;
use EsiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * KillmailsApiTest Class Doc Comment
 *
 * @package  EsiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class KillmailsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getCharactersCharacterIdKillmailsRecent
     *
     * Get a character's recent kills and losses.
     *
     */
    public function testGetCharactersCharacterIdKillmailsRecent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCorporationsCorporationIdKillmailsRecent
     *
     * Get a corporation's recent kills and losses.
     *
     */
    public function testGetCorporationsCorporationIdKillmailsRecent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getKillmailsKillmailIdKillmailHash
     *
     * Get a single killmail.
     *
     */
    public function testGetKillmailsKillmailIdKillmailHash()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
