<?php
/**
 * WalletApiTest
 * PHP version 8.1
 *
 * @package  EsiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.33
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace EsiClient\Test\Api;

use EsiClient\Configuration;
use EsiClient\ApiException;
use EsiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * WalletApiTest Class Doc Comment
 *
 * @package  EsiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WalletApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getCharactersCharacterIdWallet
     *
     * Get a character's wallet balance.
     *
     */
    public function testGetCharactersCharacterIdWallet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCharactersCharacterIdWalletJournal
     *
     * Get character wallet journal.
     *
     */
    public function testGetCharactersCharacterIdWalletJournal()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCharactersCharacterIdWalletTransactions
     *
     * Get wallet transactions.
     *
     */
    public function testGetCharactersCharacterIdWalletTransactions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCorporationsCorporationIdWallets
     *
     * Returns a corporation's wallet balance.
     *
     */
    public function testGetCorporationsCorporationIdWallets()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCorporationsCorporationIdWalletsDivisionJournal
     *
     * Get corporation wallet journal.
     *
     */
    public function testGetCorporationsCorporationIdWalletsDivisionJournal()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCorporationsCorporationIdWalletsDivisionTransactions
     *
     * Get corporation wallet transactions.
     *
     */
    public function testGetCorporationsCorporationIdWalletsDivisionTransactions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
