<?php
/**
 * WarsApiTest
 * PHP version 8.1
 *
 * @package  EsiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.33
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace EsiClient\Test\Api;

use EsiClient\Configuration;
use EsiClient\ApiException;
use EsiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * WarsApiTest Class Doc Comment
 *
 * @package  EsiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WarsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getWars
     *
     * List wars.
     *
     */
    public function testGetWars()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWarsWarId
     *
     * Get war information.
     *
     */
    public function testGetWarsWarId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWarsWarIdKillmails
     *
     * List kills for a war.
     *
     */
    public function testGetWarsWarIdKillmails()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
