<?php
/**
 * GetFwLeaderboardsCorporationsVictoryPoints
 *
 * PHP version 8.1
 *
 * @package  EsiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.33
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EsiClient\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use EsiClient\ObjectSerializer;

/**
 * GetFwLeaderboardsCorporationsVictoryPoints Class Doc Comment
 *
 * @description Top 10 rankings of corporations by victory points from yesterday, last week and in total
 * @package  EsiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class GetFwLeaderboardsCorporationsVictoryPoints implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'get_fw_leaderboards_corporations_victory_points';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'active_total' => '\EsiClient\Model\GetFwLeaderboardsCorporationsActiveTotalActiveTotal1[]',
        'last_week' => '\EsiClient\Model\GetFwLeaderboardsCorporationsLastWeekLastWeek1[]',
        'yesterday' => '\EsiClient\Model\GetFwLeaderboardsCorporationsYesterdayYesterday1[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'active_total' => null,
        'last_week' => null,
        'yesterday' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'active_total' => false,
        'last_week' => false,
        'yesterday' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'active_total' => 'active_total',
        'last_week' => 'last_week',
        'yesterday' => 'yesterday'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'active_total' => 'setActiveTotal',
        'last_week' => 'setLastWeek',
        'yesterday' => 'setYesterday'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'active_total' => 'getActiveTotal',
        'last_week' => 'getLastWeek',
        'yesterday' => 'getYesterday'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('active_total', $data ?? [], null);
        $this->setIfExists('last_week', $data ?? [], null);
        $this->setIfExists('yesterday', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['active_total'] === null) {
            $invalidProperties[] = "'active_total' can't be null";
        }
        if ((count($this->container['active_total']) > 10)) {
            $invalidProperties[] = "invalid value for 'active_total', number of items must be less than or equal to 10.";
        }

        if ($this->container['last_week'] === null) {
            $invalidProperties[] = "'last_week' can't be null";
        }
        if ((count($this->container['last_week']) > 10)) {
            $invalidProperties[] = "invalid value for 'last_week', number of items must be less than or equal to 10.";
        }

        if ($this->container['yesterday'] === null) {
            $invalidProperties[] = "'yesterday' can't be null";
        }
        if ((count($this->container['yesterday']) > 10)) {
            $invalidProperties[] = "invalid value for 'yesterday', number of items must be less than or equal to 10.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets active_total
     *
     * @return \EsiClient\Model\GetFwLeaderboardsCorporationsActiveTotalActiveTotal1[]
     */
    public function getActiveTotal(): array
    {
        return $this->container['active_total'];
    }

    /**
     * Sets active_total
     *
     * @param \EsiClient\Model\GetFwLeaderboardsCorporationsActiveTotalActiveTotal1[] $active_total Top 10 ranking of corporations active in faction warfare by total victory points. A corporation is considered \"active\" if they have participated in faction warfare in the past 14 days
     *
     * @return $this
     */
    public function setActiveTotal(array $active_total): static
    {
        if (is_null($active_total)) {
            throw new InvalidArgumentException('non-nullable active_total cannot be null');
        }

        if ((count($active_total) > 10)) {
            throw new InvalidArgumentException('invalid value for $active_total when calling GetFwLeaderboardsCorporationsVictoryPoints., number of items must be less than or equal to 10.');
        }
        $this->container['active_total'] = $active_total;

        return $this;
    }

    /**
     * Gets last_week
     *
     * @return \EsiClient\Model\GetFwLeaderboardsCorporationsLastWeekLastWeek1[]
     */
    public function getLastWeek(): array
    {
        return $this->container['last_week'];
    }

    /**
     * Sets last_week
     *
     * @param \EsiClient\Model\GetFwLeaderboardsCorporationsLastWeekLastWeek1[] $last_week Top 10 ranking of corporations by victory points in the past week
     *
     * @return $this
     */
    public function setLastWeek(array $last_week): static
    {
        if (is_null($last_week)) {
            throw new InvalidArgumentException('non-nullable last_week cannot be null');
        }

        if ((count($last_week) > 10)) {
            throw new InvalidArgumentException('invalid value for $last_week when calling GetFwLeaderboardsCorporationsVictoryPoints., number of items must be less than or equal to 10.');
        }
        $this->container['last_week'] = $last_week;

        return $this;
    }

    /**
     * Gets yesterday
     *
     * @return \EsiClient\Model\GetFwLeaderboardsCorporationsYesterdayYesterday1[]
     */
    public function getYesterday(): array
    {
        return $this->container['yesterday'];
    }

    /**
     * Sets yesterday
     *
     * @param \EsiClient\Model\GetFwLeaderboardsCorporationsYesterdayYesterday1[] $yesterday Top 10 ranking of corporations by victory points in the past day
     *
     * @return $this
     */
    public function setYesterday(array $yesterday): static
    {
        if (is_null($yesterday)) {
            throw new InvalidArgumentException('non-nullable yesterday cannot be null');
        }

        if ((count($yesterday) > 10)) {
            throw new InvalidArgumentException('invalid value for $yesterday when calling GetFwLeaderboardsCorporationsVictoryPoints., number of items must be less than or equal to 10.');
        }
        $this->container['yesterday'] = $yesterday;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


