<?php
/**
 * UserInterfaceApi
 * PHP version 8.1
 *
 * @package  EsiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.33
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EsiClient\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use EsiClient\ApiException;
use EsiClient\Configuration;
use EsiClient\HeaderSelector;
use EsiClient\FormDataProcessor;
use EsiClient\ObjectSerializer;

/**
 * UserInterfaceApi Class Doc Comment
 *
 * @package  EsiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UserInterfaceApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'postUiAutopilotWaypoint' => [
            'application/json',
        ],
        'postUiOpenwindowContract' => [
            'application/json',
        ],
        'postUiOpenwindowInformation' => [
            'application/json',
        ],
        'postUiOpenwindowMarketdetails' => [
            'application/json',
        ],
        'postUiOpenwindowNewmail' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation postUiAutopilotWaypoint
     *
     * Set Autopilot Waypoint
     *
     * @param  bool $add_to_beginning Whether this solar system should be added to the beginning of all waypoints (required)
     * @param  bool $clear_other_waypoints Whether clean other waypoints beforing adding this one (required)
     * @param  int $destination_id The destination to travel to, can be solar system, station or structure&#39;s id (required)
     * @param  string|null $datasource The server name you would like data from (optional, default to 'tranquility')
     * @param  string|null $token Access token to use if unable to set a header (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postUiAutopilotWaypoint'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \EsiClient\Model\BadRequest|\EsiClient\Model\Unauthorized|\EsiClient\Model\Forbidden|\EsiClient\Model\ErrorLimited|\EsiClient\Model\InternalServerError|\EsiClient\Model\ServiceUnavailable|\EsiClient\Model\GatewayTimeout
     */
    public function postUiAutopilotWaypoint(
        bool $add_to_beginning,
        bool $clear_other_waypoints,
        int $destination_id,
        ?string $datasource = 'tranquility',
        ?string $token = null,
        string $contentType = self::contentTypes['postUiAutopilotWaypoint'][0]
    ): \EsiClient\Model\BadRequest|\EsiClient\Model\Unauthorized|\EsiClient\Model\Forbidden|\EsiClient\Model\ErrorLimited|\EsiClient\Model\InternalServerError|\EsiClient\Model\ServiceUnavailable|\EsiClient\Model\GatewayTimeout
    {
        list($response) = $this->postUiAutopilotWaypointWithHttpInfo($add_to_beginning, $clear_other_waypoints, $destination_id, $datasource, $token, $contentType);
        return $response;
    }

    /**
     * Operation postUiAutopilotWaypointWithHttpInfo
     *
     * Set Autopilot Waypoint
     *
     * @param  bool $add_to_beginning Whether this solar system should be added to the beginning of all waypoints (required)
     * @param  bool $clear_other_waypoints Whether clean other waypoints beforing adding this one (required)
     * @param  int $destination_id The destination to travel to, can be solar system, station or structure&#39;s id (required)
     * @param  string|null $datasource The server name you would like data from (optional, default to 'tranquility')
     * @param  string|null $token Access token to use if unable to set a header (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postUiAutopilotWaypoint'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function postUiAutopilotWaypointWithHttpInfo(
        bool $add_to_beginning,
        bool $clear_other_waypoints,
        int $destination_id,
        ?string $datasource = 'tranquility',
        ?string $token = null,
        string $contentType = self::contentTypes['postUiAutopilotWaypoint'][0]
    ): array
    {
        $request = $this->postUiAutopilotWaypointRequest($add_to_beginning, $clear_other_waypoints, $destination_id, $datasource, $token, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\BadRequest',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\Unauthorized',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\Forbidden',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 420:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\ErrorLimited',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\InternalServerError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\ServiceUnavailable',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 504:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\GatewayTimeout',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation postUiAutopilotWaypointAsync
     *
     * Set Autopilot Waypoint
     *
     * @param  bool $add_to_beginning Whether this solar system should be added to the beginning of all waypoints (required)
     * @param  bool $clear_other_waypoints Whether clean other waypoints beforing adding this one (required)
     * @param  int $destination_id The destination to travel to, can be solar system, station or structure&#39;s id (required)
     * @param  string|null $datasource The server name you would like data from (optional, default to 'tranquility')
     * @param  string|null $token Access token to use if unable to set a header (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postUiAutopilotWaypoint'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function postUiAutopilotWaypointAsync(
        bool $add_to_beginning,
        bool $clear_other_waypoints,
        int $destination_id,
        ?string $datasource = 'tranquility',
        ?string $token = null,
        string $contentType = self::contentTypes['postUiAutopilotWaypoint'][0]
    ): PromiseInterface
    {
        return $this->postUiAutopilotWaypointAsyncWithHttpInfo($add_to_beginning, $clear_other_waypoints, $destination_id, $datasource, $token, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postUiAutopilotWaypointAsyncWithHttpInfo
     *
     * Set Autopilot Waypoint
     *
     * @param  bool $add_to_beginning Whether this solar system should be added to the beginning of all waypoints (required)
     * @param  bool $clear_other_waypoints Whether clean other waypoints beforing adding this one (required)
     * @param  int $destination_id The destination to travel to, can be solar system, station or structure&#39;s id (required)
     * @param  string|null $datasource The server name you would like data from (optional, default to 'tranquility')
     * @param  string|null $token Access token to use if unable to set a header (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postUiAutopilotWaypoint'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function postUiAutopilotWaypointAsyncWithHttpInfo(
        bool $add_to_beginning,
        bool $clear_other_waypoints,
        int $destination_id,
        ?string $datasource = 'tranquility',
        ?string $token = null,
        string $contentType = self::contentTypes['postUiAutopilotWaypoint'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->postUiAutopilotWaypointRequest($add_to_beginning, $clear_other_waypoints, $destination_id, $datasource, $token, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postUiAutopilotWaypoint'
     *
     * @param  bool $add_to_beginning Whether this solar system should be added to the beginning of all waypoints (required)
     * @param  bool $clear_other_waypoints Whether clean other waypoints beforing adding this one (required)
     * @param  int $destination_id The destination to travel to, can be solar system, station or structure&#39;s id (required)
     * @param  string|null $datasource The server name you would like data from (optional, default to 'tranquility')
     * @param  string|null $token Access token to use if unable to set a header (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postUiAutopilotWaypoint'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postUiAutopilotWaypointRequest(
        bool $add_to_beginning,
        bool $clear_other_waypoints,
        int $destination_id,
        ?string $datasource = 'tranquility',
        ?string $token = null,
        string $contentType = self::contentTypes['postUiAutopilotWaypoint'][0]
    ): Request
    {

        // verify the required parameter 'add_to_beginning' is set
        if ($add_to_beginning === null || (is_array($add_to_beginning) && count($add_to_beginning) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $add_to_beginning when calling postUiAutopilotWaypoint'
            );
        }

        // verify the required parameter 'clear_other_waypoints' is set
        if ($clear_other_waypoints === null || (is_array($clear_other_waypoints) && count($clear_other_waypoints) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $clear_other_waypoints when calling postUiAutopilotWaypoint'
            );
        }

        // verify the required parameter 'destination_id' is set
        if ($destination_id === null || (is_array($destination_id) && count($destination_id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $destination_id when calling postUiAutopilotWaypoint'
            );
        }




        $resourcePath = '/ui/autopilot/waypoint/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $add_to_beginning,
            'add_to_beginning', // param base name
            'boolean', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $clear_other_waypoints,
            'clear_other_waypoints', // param base name
            'boolean', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $datasource,
            'datasource', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $destination_id,
            'destination_id', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $token,
            'token', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postUiOpenwindowContract
     *
     * Open Contract Window
     *
     * @param  int $contract_id The contract to open (required)
     * @param  string|null $datasource The server name you would like data from (optional, default to 'tranquility')
     * @param  string|null $token Access token to use if unable to set a header (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postUiOpenwindowContract'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \EsiClient\Model\BadRequest|\EsiClient\Model\Unauthorized|\EsiClient\Model\Forbidden|\EsiClient\Model\ErrorLimited|\EsiClient\Model\InternalServerError|\EsiClient\Model\ServiceUnavailable|\EsiClient\Model\GatewayTimeout
     */
    public function postUiOpenwindowContract(
        int $contract_id,
        ?string $datasource = 'tranquility',
        ?string $token = null,
        string $contentType = self::contentTypes['postUiOpenwindowContract'][0]
    ): \EsiClient\Model\BadRequest|\EsiClient\Model\Unauthorized|\EsiClient\Model\Forbidden|\EsiClient\Model\ErrorLimited|\EsiClient\Model\InternalServerError|\EsiClient\Model\ServiceUnavailable|\EsiClient\Model\GatewayTimeout
    {
        list($response) = $this->postUiOpenwindowContractWithHttpInfo($contract_id, $datasource, $token, $contentType);
        return $response;
    }

    /**
     * Operation postUiOpenwindowContractWithHttpInfo
     *
     * Open Contract Window
     *
     * @param  int $contract_id The contract to open (required)
     * @param  string|null $datasource The server name you would like data from (optional, default to 'tranquility')
     * @param  string|null $token Access token to use if unable to set a header (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postUiOpenwindowContract'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function postUiOpenwindowContractWithHttpInfo(
        int $contract_id,
        ?string $datasource = 'tranquility',
        ?string $token = null,
        string $contentType = self::contentTypes['postUiOpenwindowContract'][0]
    ): array
    {
        $request = $this->postUiOpenwindowContractRequest($contract_id, $datasource, $token, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\BadRequest',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\Unauthorized',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\Forbidden',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 420:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\ErrorLimited',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\InternalServerError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\ServiceUnavailable',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 504:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\GatewayTimeout',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation postUiOpenwindowContractAsync
     *
     * Open Contract Window
     *
     * @param  int $contract_id The contract to open (required)
     * @param  string|null $datasource The server name you would like data from (optional, default to 'tranquility')
     * @param  string|null $token Access token to use if unable to set a header (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postUiOpenwindowContract'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function postUiOpenwindowContractAsync(
        int $contract_id,
        ?string $datasource = 'tranquility',
        ?string $token = null,
        string $contentType = self::contentTypes['postUiOpenwindowContract'][0]
    ): PromiseInterface
    {
        return $this->postUiOpenwindowContractAsyncWithHttpInfo($contract_id, $datasource, $token, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postUiOpenwindowContractAsyncWithHttpInfo
     *
     * Open Contract Window
     *
     * @param  int $contract_id The contract to open (required)
     * @param  string|null $datasource The server name you would like data from (optional, default to 'tranquility')
     * @param  string|null $token Access token to use if unable to set a header (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postUiOpenwindowContract'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function postUiOpenwindowContractAsyncWithHttpInfo(
        int $contract_id,
        ?string $datasource = 'tranquility',
        ?string $token = null,
        string $contentType = self::contentTypes['postUiOpenwindowContract'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->postUiOpenwindowContractRequest($contract_id, $datasource, $token, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postUiOpenwindowContract'
     *
     * @param  int $contract_id The contract to open (required)
     * @param  string|null $datasource The server name you would like data from (optional, default to 'tranquility')
     * @param  string|null $token Access token to use if unable to set a header (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postUiOpenwindowContract'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postUiOpenwindowContractRequest(
        int $contract_id,
        ?string $datasource = 'tranquility',
        ?string $token = null,
        string $contentType = self::contentTypes['postUiOpenwindowContract'][0]
    ): Request
    {

        // verify the required parameter 'contract_id' is set
        if ($contract_id === null || (is_array($contract_id) && count($contract_id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $contract_id when calling postUiOpenwindowContract'
            );
        }




        $resourcePath = '/ui/openwindow/contract/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $contract_id,
            'contract_id', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $datasource,
            'datasource', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $token,
            'token', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postUiOpenwindowInformation
     *
     * Open Information Window
     *
     * @param  int $target_id The target to open (required)
     * @param  string|null $datasource The server name you would like data from (optional, default to 'tranquility')
     * @param  string|null $token Access token to use if unable to set a header (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postUiOpenwindowInformation'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \EsiClient\Model\BadRequest|\EsiClient\Model\Unauthorized|\EsiClient\Model\Forbidden|\EsiClient\Model\ErrorLimited|\EsiClient\Model\InternalServerError|\EsiClient\Model\ServiceUnavailable|\EsiClient\Model\GatewayTimeout
     */
    public function postUiOpenwindowInformation(
        int $target_id,
        ?string $datasource = 'tranquility',
        ?string $token = null,
        string $contentType = self::contentTypes['postUiOpenwindowInformation'][0]
    ): \EsiClient\Model\BadRequest|\EsiClient\Model\Unauthorized|\EsiClient\Model\Forbidden|\EsiClient\Model\ErrorLimited|\EsiClient\Model\InternalServerError|\EsiClient\Model\ServiceUnavailable|\EsiClient\Model\GatewayTimeout
    {
        list($response) = $this->postUiOpenwindowInformationWithHttpInfo($target_id, $datasource, $token, $contentType);
        return $response;
    }

    /**
     * Operation postUiOpenwindowInformationWithHttpInfo
     *
     * Open Information Window
     *
     * @param  int $target_id The target to open (required)
     * @param  string|null $datasource The server name you would like data from (optional, default to 'tranquility')
     * @param  string|null $token Access token to use if unable to set a header (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postUiOpenwindowInformation'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function postUiOpenwindowInformationWithHttpInfo(
        int $target_id,
        ?string $datasource = 'tranquility',
        ?string $token = null,
        string $contentType = self::contentTypes['postUiOpenwindowInformation'][0]
    ): array
    {
        $request = $this->postUiOpenwindowInformationRequest($target_id, $datasource, $token, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\BadRequest',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\Unauthorized',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\Forbidden',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 420:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\ErrorLimited',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\InternalServerError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\ServiceUnavailable',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 504:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\GatewayTimeout',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation postUiOpenwindowInformationAsync
     *
     * Open Information Window
     *
     * @param  int $target_id The target to open (required)
     * @param  string|null $datasource The server name you would like data from (optional, default to 'tranquility')
     * @param  string|null $token Access token to use if unable to set a header (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postUiOpenwindowInformation'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function postUiOpenwindowInformationAsync(
        int $target_id,
        ?string $datasource = 'tranquility',
        ?string $token = null,
        string $contentType = self::contentTypes['postUiOpenwindowInformation'][0]
    ): PromiseInterface
    {
        return $this->postUiOpenwindowInformationAsyncWithHttpInfo($target_id, $datasource, $token, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postUiOpenwindowInformationAsyncWithHttpInfo
     *
     * Open Information Window
     *
     * @param  int $target_id The target to open (required)
     * @param  string|null $datasource The server name you would like data from (optional, default to 'tranquility')
     * @param  string|null $token Access token to use if unable to set a header (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postUiOpenwindowInformation'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function postUiOpenwindowInformationAsyncWithHttpInfo(
        int $target_id,
        ?string $datasource = 'tranquility',
        ?string $token = null,
        string $contentType = self::contentTypes['postUiOpenwindowInformation'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->postUiOpenwindowInformationRequest($target_id, $datasource, $token, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postUiOpenwindowInformation'
     *
     * @param  int $target_id The target to open (required)
     * @param  string|null $datasource The server name you would like data from (optional, default to 'tranquility')
     * @param  string|null $token Access token to use if unable to set a header (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postUiOpenwindowInformation'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postUiOpenwindowInformationRequest(
        int $target_id,
        ?string $datasource = 'tranquility',
        ?string $token = null,
        string $contentType = self::contentTypes['postUiOpenwindowInformation'][0]
    ): Request
    {

        // verify the required parameter 'target_id' is set
        if ($target_id === null || (is_array($target_id) && count($target_id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $target_id when calling postUiOpenwindowInformation'
            );
        }




        $resourcePath = '/ui/openwindow/information/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $datasource,
            'datasource', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $target_id,
            'target_id', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $token,
            'token', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postUiOpenwindowMarketdetails
     *
     * Open Market Details
     *
     * @param  int $type_id The item type to open in market window (required)
     * @param  string|null $datasource The server name you would like data from (optional, default to 'tranquility')
     * @param  string|null $token Access token to use if unable to set a header (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postUiOpenwindowMarketdetails'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \EsiClient\Model\BadRequest|\EsiClient\Model\Unauthorized|\EsiClient\Model\Forbidden|\EsiClient\Model\ErrorLimited|\EsiClient\Model\InternalServerError|\EsiClient\Model\ServiceUnavailable|\EsiClient\Model\GatewayTimeout
     */
    public function postUiOpenwindowMarketdetails(
        int $type_id,
        ?string $datasource = 'tranquility',
        ?string $token = null,
        string $contentType = self::contentTypes['postUiOpenwindowMarketdetails'][0]
    ): \EsiClient\Model\BadRequest|\EsiClient\Model\Unauthorized|\EsiClient\Model\Forbidden|\EsiClient\Model\ErrorLimited|\EsiClient\Model\InternalServerError|\EsiClient\Model\ServiceUnavailable|\EsiClient\Model\GatewayTimeout
    {
        list($response) = $this->postUiOpenwindowMarketdetailsWithHttpInfo($type_id, $datasource, $token, $contentType);
        return $response;
    }

    /**
     * Operation postUiOpenwindowMarketdetailsWithHttpInfo
     *
     * Open Market Details
     *
     * @param  int $type_id The item type to open in market window (required)
     * @param  string|null $datasource The server name you would like data from (optional, default to 'tranquility')
     * @param  string|null $token Access token to use if unable to set a header (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postUiOpenwindowMarketdetails'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function postUiOpenwindowMarketdetailsWithHttpInfo(
        int $type_id,
        ?string $datasource = 'tranquility',
        ?string $token = null,
        string $contentType = self::contentTypes['postUiOpenwindowMarketdetails'][0]
    ): array
    {
        $request = $this->postUiOpenwindowMarketdetailsRequest($type_id, $datasource, $token, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\BadRequest',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\Unauthorized',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\Forbidden',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 420:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\ErrorLimited',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\InternalServerError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\ServiceUnavailable',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 504:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\GatewayTimeout',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation postUiOpenwindowMarketdetailsAsync
     *
     * Open Market Details
     *
     * @param  int $type_id The item type to open in market window (required)
     * @param  string|null $datasource The server name you would like data from (optional, default to 'tranquility')
     * @param  string|null $token Access token to use if unable to set a header (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postUiOpenwindowMarketdetails'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function postUiOpenwindowMarketdetailsAsync(
        int $type_id,
        ?string $datasource = 'tranquility',
        ?string $token = null,
        string $contentType = self::contentTypes['postUiOpenwindowMarketdetails'][0]
    ): PromiseInterface
    {
        return $this->postUiOpenwindowMarketdetailsAsyncWithHttpInfo($type_id, $datasource, $token, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postUiOpenwindowMarketdetailsAsyncWithHttpInfo
     *
     * Open Market Details
     *
     * @param  int $type_id The item type to open in market window (required)
     * @param  string|null $datasource The server name you would like data from (optional, default to 'tranquility')
     * @param  string|null $token Access token to use if unable to set a header (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postUiOpenwindowMarketdetails'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function postUiOpenwindowMarketdetailsAsyncWithHttpInfo(
        int $type_id,
        ?string $datasource = 'tranquility',
        ?string $token = null,
        string $contentType = self::contentTypes['postUiOpenwindowMarketdetails'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->postUiOpenwindowMarketdetailsRequest($type_id, $datasource, $token, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postUiOpenwindowMarketdetails'
     *
     * @param  int $type_id The item type to open in market window (required)
     * @param  string|null $datasource The server name you would like data from (optional, default to 'tranquility')
     * @param  string|null $token Access token to use if unable to set a header (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postUiOpenwindowMarketdetails'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postUiOpenwindowMarketdetailsRequest(
        int $type_id,
        ?string $datasource = 'tranquility',
        ?string $token = null,
        string $contentType = self::contentTypes['postUiOpenwindowMarketdetails'][0]
    ): Request
    {

        // verify the required parameter 'type_id' is set
        if ($type_id === null || (is_array($type_id) && count($type_id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $type_id when calling postUiOpenwindowMarketdetails'
            );
        }




        $resourcePath = '/ui/openwindow/marketdetails/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $datasource,
            'datasource', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $token,
            'token', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $type_id,
            'type_id', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postUiOpenwindowNewmail
     *
     * Open New Mail Window
     *
     * @param  \EsiClient\Model\PostUiOpenwindowNewmailNewMail $new_mail The details of mail to create (required)
     * @param  string|null $datasource The server name you would like data from (optional, default to 'tranquility')
     * @param  string|null $token Access token to use if unable to set a header (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postUiOpenwindowNewmail'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \EsiClient\Model\BadRequest|\EsiClient\Model\Unauthorized|\EsiClient\Model\Forbidden|\EsiClient\Model\ErrorLimited|\EsiClient\Model\PostUiOpenwindowNewmailUnprocessableEntity|\EsiClient\Model\InternalServerError|\EsiClient\Model\ServiceUnavailable|\EsiClient\Model\GatewayTimeout
     */
    public function postUiOpenwindowNewmail(
        \EsiClient\Model\PostUiOpenwindowNewmailNewMail $new_mail,
        ?string $datasource = 'tranquility',
        ?string $token = null,
        string $contentType = self::contentTypes['postUiOpenwindowNewmail'][0]
    ): \EsiClient\Model\BadRequest|\EsiClient\Model\Unauthorized|\EsiClient\Model\Forbidden|\EsiClient\Model\ErrorLimited|\EsiClient\Model\PostUiOpenwindowNewmailUnprocessableEntity|\EsiClient\Model\InternalServerError|\EsiClient\Model\ServiceUnavailable|\EsiClient\Model\GatewayTimeout
    {
        list($response) = $this->postUiOpenwindowNewmailWithHttpInfo($new_mail, $datasource, $token, $contentType);
        return $response;
    }

    /**
     * Operation postUiOpenwindowNewmailWithHttpInfo
     *
     * Open New Mail Window
     *
     * @param  \EsiClient\Model\PostUiOpenwindowNewmailNewMail $new_mail The details of mail to create (required)
     * @param  string|null $datasource The server name you would like data from (optional, default to 'tranquility')
     * @param  string|null $token Access token to use if unable to set a header (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postUiOpenwindowNewmail'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function postUiOpenwindowNewmailWithHttpInfo(
        \EsiClient\Model\PostUiOpenwindowNewmailNewMail $new_mail,
        ?string $datasource = 'tranquility',
        ?string $token = null,
        string $contentType = self::contentTypes['postUiOpenwindowNewmail'][0]
    ): array
    {
        $request = $this->postUiOpenwindowNewmailRequest($new_mail, $datasource, $token, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\BadRequest',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\Unauthorized',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\Forbidden',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 420:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\ErrorLimited',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\PostUiOpenwindowNewmailUnprocessableEntity',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\InternalServerError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\ServiceUnavailable',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 504:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EsiClient\Model\GatewayTimeout',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation postUiOpenwindowNewmailAsync
     *
     * Open New Mail Window
     *
     * @param  \EsiClient\Model\PostUiOpenwindowNewmailNewMail $new_mail The details of mail to create (required)
     * @param  string|null $datasource The server name you would like data from (optional, default to 'tranquility')
     * @param  string|null $token Access token to use if unable to set a header (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postUiOpenwindowNewmail'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function postUiOpenwindowNewmailAsync(
        \EsiClient\Model\PostUiOpenwindowNewmailNewMail $new_mail,
        ?string $datasource = 'tranquility',
        ?string $token = null,
        string $contentType = self::contentTypes['postUiOpenwindowNewmail'][0]
    ): PromiseInterface
    {
        return $this->postUiOpenwindowNewmailAsyncWithHttpInfo($new_mail, $datasource, $token, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postUiOpenwindowNewmailAsyncWithHttpInfo
     *
     * Open New Mail Window
     *
     * @param  \EsiClient\Model\PostUiOpenwindowNewmailNewMail $new_mail The details of mail to create (required)
     * @param  string|null $datasource The server name you would like data from (optional, default to 'tranquility')
     * @param  string|null $token Access token to use if unable to set a header (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postUiOpenwindowNewmail'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function postUiOpenwindowNewmailAsyncWithHttpInfo(
        \EsiClient\Model\PostUiOpenwindowNewmailNewMail $new_mail,
        ?string $datasource = 'tranquility',
        ?string $token = null,
        string $contentType = self::contentTypes['postUiOpenwindowNewmail'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->postUiOpenwindowNewmailRequest($new_mail, $datasource, $token, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postUiOpenwindowNewmail'
     *
     * @param  \EsiClient\Model\PostUiOpenwindowNewmailNewMail $new_mail The details of mail to create (required)
     * @param  string|null $datasource The server name you would like data from (optional, default to 'tranquility')
     * @param  string|null $token Access token to use if unable to set a header (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postUiOpenwindowNewmail'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postUiOpenwindowNewmailRequest(
        \EsiClient\Model\PostUiOpenwindowNewmailNewMail $new_mail,
        ?string $datasource = 'tranquility',
        ?string $token = null,
        string $contentType = self::contentTypes['postUiOpenwindowNewmail'][0]
    ): Request
    {

        // verify the required parameter 'new_mail' is set
        if ($new_mail === null || (is_array($new_mail) && count($new_mail) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $new_mail when calling postUiOpenwindowNewmail'
            );
        }




        $resourcePath = '/ui/openwindow/newmail/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $datasource,
            'datasource', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $token,
            'token', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($new_mail)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($new_mail));
            } else {
                $httpBody = $new_mail;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if (in_array($dataType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
