<?php
/**
 * GetKillmailsKillmailIdKillmailHashOkTest
 *
 * PHP version 8.1
 *
 * @package  EsiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.33
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace EsiClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetKillmailsKillmailIdKillmailHashOkTest Class Doc Comment
 *
 * @description 200 ok object
 * @package     EsiClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetKillmailsKillmailIdKillmailHashOkTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetKillmailsKillmailIdKillmailHashOk"
     */
    public function testGetKillmailsKillmailIdKillmailHashOk()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "attackers"
     */
    public function testPropertyAttackers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "killmail_id"
     */
    public function testPropertyKillmailId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "killmail_time"
     */
    public function testPropertyKillmailTime()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "moon_id"
     */
    public function testPropertyMoonId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "solar_system_id"
     */
    public function testPropertySolarSystemId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "victim"
     */
    public function testPropertyVictim()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "war_id"
     */
    public function testPropertyWarId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
