<?php
/**
 * GetLoyaltyStoresCorporationIdOffers200OkTest
 *
 * PHP version 8.1
 *
 * @package  EsiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.33
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace EsiClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetLoyaltyStoresCorporationIdOffers200OkTest Class Doc Comment
 *
 * @description 200 ok object
 * @package     EsiClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetLoyaltyStoresCorporationIdOffers200OkTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetLoyaltyStoresCorporationIdOffers200Ok"
     */
    public function testGetLoyaltyStoresCorporationIdOffers200Ok()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ak_cost"
     */
    public function testPropertyAkCost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "isk_cost"
     */
    public function testPropertyIskCost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "lp_cost"
     */
    public function testPropertyLpCost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "offer_id"
     */
    public function testPropertyOfferId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "required_items"
     */
    public function testPropertyRequiredItems()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "type_id"
     */
    public function testPropertyTypeId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
