<?php
/**
 * GetDogmaAttributesAttributeIdOkTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  EsiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.33
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace EsiClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetDogmaAttributesAttributeIdOkTest Class Doc Comment
 *
 * @category    Class
 * @description 200 ok object
 * @package     EsiClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetDogmaAttributesAttributeIdOkTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetDogmaAttributesAttributeIdOk"
     */
    public function testGetDogmaAttributesAttributeIdOk()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "attribute_id"
     */
    public function testPropertyAttributeId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "default_value"
     */
    public function testPropertyDefaultValue()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "display_name"
     */
    public function testPropertyDisplayName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "high_is_good"
     */
    public function testPropertyHighIsGood()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "icon_id"
     */
    public function testPropertyIconId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "published"
     */
    public function testPropertyPublished()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "stackable"
     */
    public function testPropertyStackable()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "unit_id"
     */
    public function testPropertyUnitId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
