<?php
/**
 * FactionWarfareApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  EsiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.33
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace EsiClient\Test\Api;

use \EsiClient\Configuration;
use \EsiClient\ApiException;
use \EsiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FactionWarfareApiTest Class Doc Comment
 *
 * @category Class
 * @package  EsiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FactionWarfareApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getCharactersCharacterIdFwStats
     *
     * Overview of a character involved in faction warfare.
     *
     */
    public function testGetCharactersCharacterIdFwStats()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCorporationsCorporationIdFwStats
     *
     * Overview of a corporation involved in faction warfare.
     *
     */
    public function testGetCorporationsCorporationIdFwStats()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getFwLeaderboards
     *
     * List of the top factions in faction warfare.
     *
     */
    public function testGetFwLeaderboards()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getFwLeaderboardsCharacters
     *
     * List of the top pilots in faction warfare.
     *
     */
    public function testGetFwLeaderboardsCharacters()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getFwLeaderboardsCorporations
     *
     * List of the top corporations in faction warfare.
     *
     */
    public function testGetFwLeaderboardsCorporations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getFwStats
     *
     * An overview of statistics about factions involved in faction warfare.
     *
     */
    public function testGetFwStats()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getFwSystems
     *
     * Ownership of faction warfare systems.
     *
     */
    public function testGetFwSystems()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getFwWars
     *
     * Data about which NPC factions are at war.
     *
     */
    public function testGetFwWars()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
